### ISSUE TITLE
Bug: Generates Invalid CSS

### ISSUE THREAD

**Issue by selbyk** [nknapp/bootprint-swagger#12]
Moving here from: https://github.com/nknapp/swagger-to-html/issues/3

There is a strange bug causing a tiny mistake in the CSS, making it invalid:

```css
.radio input[type="radio"],.radio-inline input[type="radio"],.checkbox input[type="checkbox"],.checkbox-inline input[type="checkbox"] {
    position:absolute;
    margin-left:-20px;
    margin-top:4px \9
}
```

It probably won't effect most people since browsers do their best not to blow up, but a parser I use is not happy about it at all. =P

```
ParseError: Unrecognised input. Possibly missing opening '{' in /home/selby/projects/tenable/front/tmp/tree_merger-tmp_dest_dir-m8uv0yEk.tmp/app/styles/docs.less on line 5, column 38385:
```

Just in case anyone else is running into a similar problem, I wrote two bash scripts as a quick fix until I or someone else can figure out what the actual problem is.

```bash
#!/bin/bash
# ./fixcss.sh
# Usage: ./fixcss.sh <file.css> <keep backup: 1 or 0>

# Lets fix some CSS
cat $1 | grep --quiet -i "\\\9" && {
  echo "CSS invalid, attempting to fix"
  rm $1.bak -f
  echo "Creating backup..."
  mv $1 $1.bak
  echo "Replacing invalid string..."
  cat $1.bak | sed -r s/\\\\9//g | tee $1 1> /dev/null
  cat $1 | grep --quiet -i "\\\9" && {
    echo "CSS still invalid, sorry =/"
    echo "Replacing original file..."
    rm $1 -f
    mv $1.bak $1
  } || echo "Good to go =)"
  $2 || echo "Removing backup..." && rm $1.bak -f
} || echo "Not broken, don't worry about it"

```

```bash
#!/bin/bash
# ./gendocs.sh
# Usage: ./gendocs.sh <swagger.json> <target_dir>

# Gets directory script is running from
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
# Generate Docs
bootprint swagger $1 $2
# Fix invalid CSS
$DIR/fixcss.sh $2/main.css

```

I keep them in my projects' `./scripts` directory and call them like `./scripts/gendocs.sh swagger.json ./docs/spec`, but you could also come up with more specific names, drop the .sh, toss them in `~/bin` and add `export PATH=$PATH:~/bin` to your `~/.bashrc` so that you can use them globally.

Hope this helps someone!  Happy coding. =)

-Selby
http://selby.io

**Comment by nknapp** [comment]
Actually, it's a good idea to write a test for that, but it should be [incorporated in the existing jasmine specs](https://github.com/nknapp/bootprint-swagger/blob/master/spec/petstore-spec.js), so that it gets executed  with the regular unit tests. 

Thanks for your input. Maybe this issue is also the reason for my problem in #8

**Comment by nknapp** [comment]
It is in bootstrap's [`forms.less`, line 51](https://github.com/twbs/bootstrap/blob/master/less/forms.less#L51):

```less
// Position radios and checkboxes better
input[type="radio"],
input[type="checkbox"] {
  margin: 4px 0 0;
  margin-top: 1px \9; // IE8-9
  line-height: normal;
}
```
